name: Linux Commands Workflow

on:
  push:

jobs:
  linux-demo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Date
        run: date

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls

      - name: Show User
        run: whoami

      - name: Print Message
        run: echo "DevOps Learning in Progress"
